apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-benchmark-gpu-monitor
  namespace: llm-benchmark
  labels:
    app: llm-benchmark
    component: gpu-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-benchmark
      component: gpu-monitor
  template:
    metadata:
      labels:
        app: llm-benchmark
        component: gpu-monitor
    spec:
      containers:
      - name: gpu-monitor
        image: image-registry.openshift-image-registry.svc:5000/llm-benchmark/llm-benchmark-gpu-monitor:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: FLASK_ENV
          value: "production"
        - name: FLASK_HOST
          value: "0.0.0.0"
        - name: FLASK_PORT
          value: "8080"
        - name: SIMULATE_GPU
          value: "true"  # Use simulated GPU data for sandbox environment
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: llm-benchmark-gpu-monitor-service
  namespace: llm-benchmark
  labels:
    app: llm-benchmark
    component: gpu-monitor
spec:
  selector:
    app: llm-benchmark
    component: gpu-monitor
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llm-benchmark-gpu-monitor-route
  namespace: llm-benchmark
  labels:
    app: llm-benchmark
    component: gpu-monitor
spec:
  to:
    kind: Service
    name: llm-benchmark-gpu-monitor-service
  port:
    targetPort: http

  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect 